//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logica.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServicio")]
    public interface IServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AgregarArticulo", ReplyAction="http://tempuri.org/IServicio/AgregarArticuloResponse")]
        void AgregarArticulo(EntidadesCompartidas.Articulo A, EntidadesCompartidas.Usuario u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AgregarArticulo", ReplyAction="http://tempuri.org/IServicio/AgregarArticuloResponse")]
        System.Threading.Tasks.Task AgregarArticuloAsync(EntidadesCompartidas.Articulo A, EntidadesCompartidas.Usuario u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EliminarArticulo", ReplyAction="http://tempuri.org/IServicio/EliminarArticuloResponse")]
        void EliminarArticulo(EntidadesCompartidas.Articulo A);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EliminarArticulo", ReplyAction="http://tempuri.org/IServicio/EliminarArticuloResponse")]
        System.Threading.Tasks.Task EliminarArticuloAsync(EntidadesCompartidas.Articulo A);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ModificarArticulo", ReplyAction="http://tempuri.org/IServicio/ModificarArticuloResponse")]
        void ModificarArticulo(EntidadesCompartidas.Articulo A);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ModificarArticulo", ReplyAction="http://tempuri.org/IServicio/ModificarArticuloResponse")]
        System.Threading.Tasks.Task ModificarArticuloAsync(EntidadesCompartidas.Articulo A);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarArticulo", ReplyAction="http://tempuri.org/IServicio/BuscarArticuloResponse")]
        EntidadesCompartidas.Articulo BuscarArticulo(int pCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarArticulo", ReplyAction="http://tempuri.org/IServicio/BuscarArticuloResponse")]
        System.Threading.Tasks.Task<EntidadesCompartidas.Articulo> BuscarArticuloAsync(int pCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarArticulo", ReplyAction="http://tempuri.org/IServicio/ListarArticuloResponse")]
        EntidadesCompartidas.Articulo[] ListarArticulo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarArticulo", ReplyAction="http://tempuri.org/IServicio/ListarArticuloResponse")]
        System.Threading.Tasks.Task<EntidadesCompartidas.Articulo[]> ListarArticuloAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AgregarFactura", ReplyAction="http://tempuri.org/IServicio/AgregarFacturaResponse")]
        void AgregarFactura(EntidadesCompartidas.Factura F);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AgregarFactura", ReplyAction="http://tempuri.org/IServicio/AgregarFacturaResponse")]
        System.Threading.Tasks.Task AgregarFacturaAsync(EntidadesCompartidas.Factura F);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarFacturas", ReplyAction="http://tempuri.org/IServicio/ListarFacturasResponse")]
        EntidadesCompartidas.Factura[] ListarFacturas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarFacturas", ReplyAction="http://tempuri.org/IServicio/ListarFacturasResponse")]
        System.Threading.Tasks.Task<EntidadesCompartidas.Factura[]> ListarFacturasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/Logueo", ReplyAction="http://tempuri.org/IServicio/LogueoResponse")]
        void Logueo(EntidadesCompartidas.Usuario U);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/Logueo", ReplyAction="http://tempuri.org/IServicio/LogueoResponse")]
        System.Threading.Tasks.Task LogueoAsync(EntidadesCompartidas.Usuario U);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscoUsuario", ReplyAction="http://tempuri.org/IServicio/BuscoUsuarioResponse")]
        EntidadesCompartidas.Usuario BuscoUsuario(string pUsu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscoUsuario", ReplyAction="http://tempuri.org/IServicio/BuscoUsuarioResponse")]
        System.Threading.Tasks.Task<EntidadesCompartidas.Usuario> BuscoUsuarioAsync(string pUsu);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChannel : Logica.ServiceReference1.IServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<Logica.ServiceReference1.IServicio>, Logica.ServiceReference1.IServicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AgregarArticulo(EntidadesCompartidas.Articulo A, EntidadesCompartidas.Usuario u) {
            base.Channel.AgregarArticulo(A, u);
        }
        
        public System.Threading.Tasks.Task AgregarArticuloAsync(EntidadesCompartidas.Articulo A, EntidadesCompartidas.Usuario u) {
            return base.Channel.AgregarArticuloAsync(A, u);
        }
        
        public void EliminarArticulo(EntidadesCompartidas.Articulo A) {
            base.Channel.EliminarArticulo(A);
        }
        
        public System.Threading.Tasks.Task EliminarArticuloAsync(EntidadesCompartidas.Articulo A) {
            return base.Channel.EliminarArticuloAsync(A);
        }
        
        public void ModificarArticulo(EntidadesCompartidas.Articulo A) {
            base.Channel.ModificarArticulo(A);
        }
        
        public System.Threading.Tasks.Task ModificarArticuloAsync(EntidadesCompartidas.Articulo A) {
            return base.Channel.ModificarArticuloAsync(A);
        }
        
        public EntidadesCompartidas.Articulo BuscarArticulo(int pCodigo) {
            return base.Channel.BuscarArticulo(pCodigo);
        }
        
        public System.Threading.Tasks.Task<EntidadesCompartidas.Articulo> BuscarArticuloAsync(int pCodigo) {
            return base.Channel.BuscarArticuloAsync(pCodigo);
        }
        
        public EntidadesCompartidas.Articulo[] ListarArticulo() {
            return base.Channel.ListarArticulo();
        }
        
        public System.Threading.Tasks.Task<EntidadesCompartidas.Articulo[]> ListarArticuloAsync() {
            return base.Channel.ListarArticuloAsync();
        }
        
        public void AgregarFactura(EntidadesCompartidas.Factura F) {
            base.Channel.AgregarFactura(F);
        }
        
        public System.Threading.Tasks.Task AgregarFacturaAsync(EntidadesCompartidas.Factura F) {
            return base.Channel.AgregarFacturaAsync(F);
        }
        
        public EntidadesCompartidas.Factura[] ListarFacturas() {
            return base.Channel.ListarFacturas();
        }
        
        public System.Threading.Tasks.Task<EntidadesCompartidas.Factura[]> ListarFacturasAsync() {
            return base.Channel.ListarFacturasAsync();
        }
        
        public void Logueo(EntidadesCompartidas.Usuario U) {
            base.Channel.Logueo(U);
        }
        
        public System.Threading.Tasks.Task LogueoAsync(EntidadesCompartidas.Usuario U) {
            return base.Channel.LogueoAsync(U);
        }
        
        public EntidadesCompartidas.Usuario BuscoUsuario(string pUsu) {
            return base.Channel.BuscoUsuario(pUsu);
        }
        
        public System.Threading.Tasks.Task<EntidadesCompartidas.Usuario> BuscoUsuarioAsync(string pUsu) {
            return base.Channel.BuscoUsuarioAsync(pUsu);
        }
    }
}
